// <auto-generated />
using System;
using GamingCenter.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamingCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212110055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamingCenter.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.PC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PC", (string)null);
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PCId")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("Price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PCId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.Membership", b =>
                {
                    b.OwnsOne("GamingCenter.Domain.ValueObjects.Membership.DiscountPercentage", "DiscountPercentage", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("DiscountPercentage");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Membership");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.Membership.HoursThreshold", "HoursThreshold", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("HoursThreshold");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Membership");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.Membership.MemberShipTitle", "MembershipName", b1 =>
                        {
                            b1.Property<Guid>("MembershipId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MemberShipTitle");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Membership");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("DiscountPercentage")
                        .IsRequired();

                    b.Navigation("HoursThreshold")
                        .IsRequired();

                    b.Navigation("MembershipName")
                        .IsRequired();
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.PC", b =>
                {
                    b.OwnsOne("GamingCenter.Domain.ValueObjects.PC.Cost", "Cost", b1 =>
                        {
                            b1.Property<Guid>("PCId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("Cost");

                            b1.Property<string>("currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Currency");

                            b1.HasKey("PCId");

                            b1.ToTable("PC");

                            b1.WithOwner()
                                .HasForeignKey("PCId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.PC.PerformanceRate", "Performance", b1 =>
                        {
                            b1.Property<Guid>("PCId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Performance");

                            b1.HasKey("PCId");

                            b1.ToTable("PC");

                            b1.WithOwner()
                                .HasForeignKey("PCId");
                        });

                    b.Navigation("Cost")
                        .IsRequired();

                    b.Navigation("Performance")
                        .IsRequired();
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("GamingCenter.Domain.Entities.PC", "PC")
                        .WithMany("Reservations")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCenter.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.Reservation.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Duration");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservation");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.Reservation.ReservationTimeFrame", "TimeFrame", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndTime");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservation");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("PC");

                    b.Navigation("TimeFrame")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.User", b =>
                {
                    b.HasOne("GamingCenter.Domain.Entities.Membership", "Membership")
                        .WithMany("Users")
                        .HasForeignKey("MembershipId");

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.DoB", "DoB", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DateOfbirth");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.ProfileImage", "ProfileImage", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("ProfileImage");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("GamingCenter.Domain.ValueObjects.User.TotalPlayTime", "TotalPlaytimeHours", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalTimePlayed");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("DoB")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("ProfileImage");

                    b.Navigation("TotalPlaytimeHours")
                        .IsRequired();
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.PC", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GamingCenter.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
